---
development:
  cloud_name: dl9ktbeoh
  api_key: '824158278391182'
  api_secret: m5nuTqk6FvWiY7JAjl7fdskezyI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dl9ktbeoh
  api_key: '824158278391182'
  api_secret: m5nuTqk6FvWiY7JAjl7fdskezyI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dl9ktbeoh
  api_key: '824158278391182'
  api_secret: m5nuTqk6FvWiY7JAjl7fdskezyI
  enhance_image_tag: true
  static_image_support: false
